name: flutter_deta
description: Flutter package for easy usage of Deta Base, Drive and Auth
version: 0.0.1
homepage: https://deta.sh


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  json_serializable: ^5.0.0
  dotenv: ^3.0.0
  test: ^1.17.10
