name: deta_dart
description: Flutter package for easy usage of Deta Base, Drive and Auth
version: 1.0.2
homepage: https://deta.sh
repository: https://github.com/liquidiert/deta_dart
issue_tracker: https://github.com/liquidiert/deta_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  dotenv: ^3.0.0
  test: ^1.17.10
